#!/bin/sh
cd bin
jar cmf ../manif ../diffr.jar Org/netlib/math/complex/*.class de/berlios/diffr/*.class de/berlios/diffr/exceptions/*.class de/berlios/diffr/algorithms/*.class de/berlios/diffr/algorithms/addedAlgorithms/*.class de/berlios/diffr/inputData/*.class de/berlios/diffr/inputData/surface/*.class de/berlios/diffr/result/*.class de/berlios/diffr/task/*.class
